TrajectoryPlannerROS:
    max_vel_x: 3
    min_vel_x: 0.1
    max_rotational_vel: 1.0
    min_in_place_rotational_vel: 0.4

    acc_lim_theta: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 2.5

    xy_goal_tolerance: 0.30
    yaw_goal_tolerance: 0.15
    latch_xy_goal_tolerance: true

    holonomic_robot: false

    sim_time: 1.5
    vx_samples: 6
    vtheta_samples: 30

    meter_scoring: true

    dwa: true
    pdist_scale: 0.6
    gdist_scale: 0.8
    occdist_scale: 0.05

    controller_patience: 3.0
    oscillation_timeout: 5.0
    max_planning_retries: 100
