obstacle_range: 3.0
raytrace_range: 5.0
footprint: [[0.30, 0.25], [0.30, -0.25], [-0.30, -0.25], [-0.30, 0.25]]
inflation_radius: 0.5
transform_tolerance: 0.5
observation_sources: laser_scan_sensor point_cloud_sensor 
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: hokuyo3d, data_type: PointCloud, topic: edge_filter, marking: true, clearing: true}

